### ISSUE TITLE
Make all views use the new UI (or remove them)

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#144]
We want to make all the views use the new UI, even if it's in a very rudimentary way, so that the site doesn't look "frankensteined" such that some pages use the old Bootstrap-based look-and-feel while others use the new UI.

Things left to do:
- [x] Convert the landing page (#143)
- [x] Convert the about page (#135)
- [x] Convert the "edit my profile" page (#145)
- [x] Convert the feedback page (#146)
- [x] ~~Convert or~~ remove the `/match` and `/match-knn` endpoints (#147)
  * ~~It seems like the functionality here is being altered so much that we may want to consider just removing these pages entirely for now, and having the "Match Me" link from the base ui nav take the user to a "sorry, not implemented yet" view similar to the "View network" view.~~
- [x] Remove the `/users/recent` endpoint (#147)
- [x] Add GA tracking code to `app/templates/__base_new__.html` (#147)
- [x] Add Typekit to `app/templates/__base_new__.html` (#147)

Once all these are done, we'll want to fully remove all the assets for the old UI theme, which *I think* includes:
- [x] `app/templates/search-results.html` (#147)
- [x] `app/templates/__base__.html` (#147)
- [x] `app/templates/__navbar__.html` (#147)
- [x] `app/templates/__footer__.html` (#147)
- [x] `app/templates/security/_macros.html` (#147)
- [x] `app/templates/security/_menu.html` (#147)
- [x] `app/templates/security/_messages.html` (#147)
- [x] `app/static/normalize.css` (new UI uses the one under `/vendor/`) (#147)
- [x] The entire `app/static/styles` directory (#147)
- [x] The entire `app/static/chosen_v1.4.2` directory (as chosen isn't mobile-friendly) (#145)
- [x] A bunch of (but not *all*) the images in `app/static/img` (#147)
