### ISSUE TITLE
Get rid of unused view code

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#65]
There's a number of unused views and commented-out sections of view code that could use some removing to make the codebase a bit easier to understand and maintain, especially as we get ready to merge in claudio's new UI look-and-feel:

- [x] `base.html` is just an empty page that says "This is a test page". Can we get rid of it? (#68)
- [x] `/dashboard` renders `dashboard.html`, which has a map on it. It doesn't seem to be linked from anywhere, though; can we get rid of it? (#66)
- [x] `login-page.html` seems to be some kind of social sign-on page, allowing users to sign in using their favorite social network. AFAIK, this isn't accessible from anywhere on the current site--can we get rid of it? (#69)
- [x] In `main.html` there's some JS referring to `hello(idp).logout`; is this also related to now-defunct social sign-on functionality or something? Can we remove it? (#69)
- [x] `my-profile.html` has a bunch of commented-out code that appears to integrate with google maps location typeahead or something. Can it be removed? (#67)
- [X] `search.html` also seems to have a fair amount of commented-out code; can it be removed? (#140)
- [X] `user-profile.html` also seems to have a fair amount of commented-out code; can it be removed? (#106)
- [x] In `views.py`, there's some commented-out code for a `'/vcard/<userid>'` route; can it be removed? (#66)
- [x] What's the difference between the `match` and `knn` view? Can either be removed? (#147)
- [x] Should the `recent_users` view be removed? (#147)

**Comment by toolness** [comment]
Wooooot the front-end feels so much cleaner now! :grin:

**Comment by talos** [comment]
:sparkles: :toilet:
